import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { DM_Sans } from "next/font/google";
import { SidebarProvider } from "@/context/sidebarContext";
import "./globals.css";
import { NotifProvider } from "@/context/notifContext";
import MainLayout from "@/components/layout/mainLayout";
import { AuthProvider } from "@/context/authContext";
import { FulfillmentProvider } from "@/context/FulfillmentContext";
import { Toaster } from "sonner";
import { RootLayoutWrapper } from "@/components/layout/rootLayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DarahTanyoe - Mitra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <SidebarProvider>
          <NotifProvider>
            <FulfillmentProvider>
              <body className={`${dmSans.className} antialiased bg-primary`}>
                <Toaster position="top-right" richColors />
                <RootLayoutWrapper>{children}</RootLayoutWrapper>
              </body>
            </FulfillmentProvider>
          </NotifProvider>
        </SidebarProvider>
      </AuthProvider>
    </html>
  );
}
